name: CI Build, Test and Coverage Check

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Dagger
        run: node build.mjs

      - name: Run Unit Tests with Coverage
        run: npm run test:coverage

      - name: Check Coverage Threshold
        run: nyc check-coverage --branches 80
